import { api } from "./api";
import { normalizePendingInteraction } from "../PAGEs/chat/hooks/durable_interaction_recovery";
import fixtures from "../COMPONENTs/chat-bubble/interact/__fixtures__/human_input_free_text.json";

// Generated by the real Unchain request and PuPu host projection/response producers.
const copy = (value) => JSON.parse(JSON.stringify(value));
const mutatePayload = (pending, mutate) => {
  for (const tool of [pending.presentation.tool_call, pending.presentation.trace_frame.payload]) {
    mutate(tool.arguments);
    mutate(tool.interact_config);
  }
};

describe("free-text pending interaction boundary", () => {
  const originalBridge = window.unchainAPI;
  beforeEach(() => {
    window.unchainAPI = { getPendingInteraction: jest.fn() };
  });
  afterAll(() => { window.unchainAPI = originalBridge; });

  test.each(Object.keys(fixtures))( "%s real producer projection passes API and recovery", async (mode) => {
    const pending = copy(fixtures[mode].pending);
    window.unchainAPI.getPendingInteraction.mockResolvedValue(pending);
    const accepted = await api.unchain.getPendingInteraction({ session_id: pending.session_id });
    expect(accepted).toEqual(pending);
    const recovered = normalizePendingInteraction(accepted, pending.session_id);
    expect(recovered).not.toBeNull();
    expect(recovered.kind).toBe("human_input");
    expect(recovered.callId).toBe(pending.presentation.tool_call.call_id);
  });

  test.each([
    ["no free-text affordance", (p) => { p.allow_other = false; }],
    ["coerced affordance", (p) => { p.allow_other = "true"; }],
    ["unknown field", (p) => { p.unexpected = true; }],
    ["unsupported kind", (p) => { p.kind = "text_input"; }],
    ["wrong request identity", (p) => { p.request_id = "other-call"; }],
    ["invalid options type", (p) => { p.options = {}; }],
    ["too many answers", (p) => { p.max_selected = 2; }],
    ["unreachable minimum", (p) => { p.min_selected = 2; }],
  ])("rejects %s at both consumers", async (_name, mutate) => {
    const pending = copy(fixtures.single.pending);
    mutatePayload(pending, mutate);
    window.unchainAPI.getPendingInteraction.mockResolvedValue(pending);
    await expect(api.unchain.getPendingInteraction({ session_id: pending.session_id }))
      .rejects.toMatchObject({ code: "invalid_pending_interaction_response" });
    expect(normalizePendingInteraction(pending, pending.session_id)).toBeNull();
  });

  test("rejects divergence between the two producer copies", async () => {
    const pending = copy(fixtures.single.pending);
    pending.presentation.tool_call.interact_config.other_placeholder = "changed";
    window.unchainAPI.getPendingInteraction.mockResolvedValue(pending);
    await expect(api.unchain.getPendingInteraction({ session_id: pending.session_id }))
      .rejects.toMatchObject({ code: "invalid_pending_interaction_response" });
    expect(normalizePendingInteraction(pending, pending.session_id)).toBeNull();
  });
});
