const { CHANNELS } = require("../shared/channels");

const PRELOAD_INVOKE_CHANNELS = Object.freeze([
  CHANNELS.APP.GET_VERSION,
  CHANNELS.UPDATE.CHECK_AND_DOWNLOAD,
  CHANNELS.UPDATE.INSTALL_NOW,
  CHANNELS.UPDATE.GET_STATE,
  CHANNELS.OLLAMA.GET_STATUS,
  CHANNELS.OLLAMA.LIST_INSTALLED_MODELS,
  CHANNELS.OLLAMA.RESTART,
  CHANNELS.OLLAMA.INSTALL,
  CHANNELS.OLLAMA.LIBRARY_SEARCH,
  CHANNELS.UNCHAIN.GET_STATUS,
  CHANNELS.UNCHAIN.GET_MODEL_CATALOG,
  CHANNELS.UNCHAIN.GET_TOOLKIT_CATALOG,
  CHANNELS.UNCHAIN.TOOL_CONFIRMATION,
  CHANNELS.UNCHAIN.SET_CHROME_TERMINAL_OPEN,
  CHANNELS.UNCHAIN.SYNC_BUILD_FEATURE_FLAGS_SNAPSHOT,
  CHANNELS.UNCHAIN.PICK_WORKSPACE_ROOT,
  CHANNELS.UNCHAIN.VALIDATE_WORKSPACE_ROOT,
  CHANNELS.UNCHAIN.OPEN_RUNTIME_FOLDER,
  CHANNELS.UNCHAIN.GET_RUNTIME_DIR_SIZE,
  CHANNELS.UNCHAIN.DELETE_RUNTIME_ENTRY,
  CHANNELS.UNCHAIN.CLEAR_RUNTIME_DIR,
  CHANNELS.UNCHAIN.REPLACE_SESSION_MEMORY,
  CHANNELS.UNCHAIN.GET_SESSION_MEMORY_EXPORT,
  CHANNELS.UNCHAIN.LIST_CHARACTERS,
  CHANNELS.UNCHAIN.GET_CHARACTER,
  CHANNELS.UNCHAIN.SAVE_CHARACTER,
  CHANNELS.UNCHAIN.DELETE_CHARACTER,
  CHANNELS.UNCHAIN.PREVIEW_CHARACTER_DECISION,
  CHANNELS.UNCHAIN.BUILD_CHARACTER_AGENT_CONFIG,
  CHANNELS.SCREENSHOT.CAPTURE,
  CHANNELS.SCREENSHOT.CHECK_AVAILABILITY,
]);

const PRELOAD_SEND_CHANNELS = Object.freeze([
  CHANNELS.UNCHAIN.STREAM_START,
  CHANNELS.UNCHAIN.STREAM_START_V2,
  CHANNELS.UNCHAIN.STREAM_CANCEL,
  CHANNELS.THEME.SET_BACKGROUND_COLOR,
  CHANNELS.THEME.SET_MODE,
  CHANNELS.WINDOW_STATE.HANDLE_ACTION,
  CHANNELS.CHAT_STORAGE.WRITE,
]);

const PRELOAD_SEND_SYNC_CHANNELS = Object.freeze([
  CHANNELS.CHAT_STORAGE.BOOTSTRAP_READ,
]);

const PRELOAD_EVENT_CHANNELS = Object.freeze([
  CHANNELS.UPDATE.STATE_CHANGED,
  CHANNELS.OLLAMA.INSTALL_PROGRESS,
  CHANNELS.UNCHAIN.STREAM_EVENT,
  CHANNELS.UNCHAIN.RUNTIME_LOG,
  CHANNELS.WINDOW_STATE.LISTENER_EVENT,
]);

module.exports = {
  PRELOAD_INVOKE_CHANNELS,
  PRELOAD_SEND_CHANNELS,
  PRELOAD_SEND_SYNC_CHANNELS,
  PRELOAD_EVENT_CHANNELS,
};
