const { CHANNELS } = require("../shared/channels");

const PRELOAD_INVOKE_CHANNELS = Object.freeze([
  CHANNELS.APP.GET_VERSION,
  CHANNELS.UPDATE.CHECK_AND_DOWNLOAD,
  CHANNELS.UPDATE.INSTALL_NOW,
  CHANNELS.UPDATE.GET_STATE,
  CHANNELS.OLLAMA.GET_STATUS,
  CHANNELS.OLLAMA.LIST_INSTALLED_MODELS,
  CHANNELS.OLLAMA.RESTART,
  CHANNELS.OLLAMA.INSTALL,
  CHANNELS.OLLAMA.LIBRARY_SEARCH,
  CHANNELS.MISO.GET_STATUS,
  CHANNELS.MISO.GET_MODEL_CATALOG,
  CHANNELS.MISO.GET_TOOLKIT_CATALOG,
  CHANNELS.MISO.TOOL_CONFIRMATION,
  CHANNELS.MISO.SET_CHROME_TERMINAL_OPEN,
  CHANNELS.MISO.PICK_WORKSPACE_ROOT,
  CHANNELS.MISO.VALIDATE_WORKSPACE_ROOT,
  CHANNELS.MISO.OPEN_RUNTIME_FOLDER,
  CHANNELS.MISO.GET_RUNTIME_DIR_SIZE,
  CHANNELS.MISO.DELETE_RUNTIME_ENTRY,
  CHANNELS.MISO.CLEAR_RUNTIME_DIR,
  CHANNELS.MISO.REPLACE_SESSION_MEMORY,
  CHANNELS.MISO.GET_SESSION_MEMORY_EXPORT,
  CHANNELS.MISO.LIST_CHARACTERS,
  CHANNELS.MISO.GET_CHARACTER,
  CHANNELS.MISO.SAVE_CHARACTER,
  CHANNELS.MISO.DELETE_CHARACTER,
  CHANNELS.MISO.PREVIEW_CHARACTER_DECISION,
  CHANNELS.MISO.BUILD_CHARACTER_AGENT_CONFIG,
]);

const PRELOAD_SEND_CHANNELS = Object.freeze([
  CHANNELS.MISO.STREAM_START,
  CHANNELS.MISO.STREAM_START_V2,
  CHANNELS.MISO.STREAM_CANCEL,
  CHANNELS.THEME.SET_BACKGROUND_COLOR,
  CHANNELS.THEME.SET_MODE,
  CHANNELS.WINDOW_STATE.HANDLE_ACTION,
]);

const PRELOAD_EVENT_CHANNELS = Object.freeze([
  CHANNELS.UPDATE.STATE_CHANGED,
  CHANNELS.OLLAMA.INSTALL_PROGRESS,
  CHANNELS.MISO.STREAM_EVENT,
  CHANNELS.MISO.RUNTIME_LOG,
  CHANNELS.WINDOW_STATE.LISTENER_EVENT,
]);

module.exports = {
  PRELOAD_INVOKE_CHANNELS,
  PRELOAD_SEND_CHANNELS,
  PRELOAD_EVENT_CHANNELS,
};
