const CHANNELS = Object.freeze({
  APP: Object.freeze({
    GET_VERSION: "app:get-version",
  }),
  CHAT_STORAGE: Object.freeze({
    BOOTSTRAP_READ: "chat-storage:bootstrap-read",
    WRITE: "chat-storage:write",
  }),
  UPDATE: Object.freeze({
    GET_STATE: "update:get-state",
    CHECK_AND_DOWNLOAD: "update:check-and-download",
    INSTALL_NOW: "update:install-now",
    STATE_CHANGED: "update:state-changed",
  }),
  OLLAMA: Object.freeze({
    GET_STATUS: "ollama-get-status",
    LIST_INSTALLED_MODELS: "ollama:list-installed-models",
    RESTART: "ollama-restart",
    INSTALL: "ollama:install",
    INSTALL_PROGRESS: "ollama:install-progress",
    LIBRARY_SEARCH: "ollama:library-search",
  }),
  UNCHAIN: Object.freeze({
    GET_STATUS: "unchain:get-status",
    GET_MODEL_CATALOG: "unchain:get-model-catalog",
    GET_TOOLKIT_CATALOG: "unchain:get-toolkit-catalog",
    LIST_TOOL_MODAL_CATALOG: "unchain:list-tool-modal-catalog",
    GET_TOOLKIT_DETAIL: "unchain:get-toolkit-detail",
    TOOL_CONFIRMATION: "unchain:tool-confirmation",
    SET_CHROME_TERMINAL_OPEN: "unchain:set-chrome-terminal-open",
    SYNC_BUILD_FEATURE_FLAGS_SNAPSHOT: "unchain:sync-build-feature-flags-snapshot",
    PICK_WORKSPACE_ROOT: "unchain:pick-workspace-root",
    VALIDATE_WORKSPACE_ROOT: "unchain:validate-workspace-root",
    OPEN_RUNTIME_FOLDER: "unchain:open-runtime-folder",
    GET_RUNTIME_DIR_SIZE: "unchain:get-runtime-dir-size",
    DELETE_RUNTIME_ENTRY: "unchain:delete-runtime-entry",
    CLEAR_RUNTIME_DIR: "unchain:clear-runtime-dir",
    GET_MEMORY_SIZE: "unchain:get-memory-size",
    GET_CHARACTER_STORAGE_SIZE: "unchain:get-character-storage-size",
    DELETE_CHARACTER_STORAGE_ENTRY: "unchain:delete-character-storage-entry",
    GET_MEMORY_PROJECTION: "unchain:get-memory-projection",
    GET_LONG_TERM_MEMORY_PROJECTION: "unchain:get-long-term-memory-projection",
    REPLACE_SESSION_MEMORY: "unchain:replace-session-memory",
    GET_SESSION_MEMORY_EXPORT: "unchain:get-session-memory-export",
    LIST_SEED_CHARACTERS: "unchain:list-seed-characters",
    LIST_CHARACTERS: "unchain:list-characters",
    GET_CHARACTER: "unchain:get-character",
    SAVE_CHARACTER: "unchain:save-character",
    DELETE_CHARACTER: "unchain:delete-character",
    LIST_RECIPES: "unchain:list-recipes",
    GET_RECIPE: "unchain:get-recipe",
    SAVE_RECIPE: "unchain:save-recipe",
    DELETE_RECIPE: "unchain:delete-recipe",
    LIST_SUBAGENT_REFS: "unchain:list-subagent-refs",
    PREVIEW_CHARACTER_DECISION: "unchain:preview-character-decision",
    BUILD_CHARACTER_AGENT_CONFIG: "unchain:build-character-agent-config",
    EXPORT_CHARACTER: "unchain:export-character",
    IMPORT_CHARACTER: "unchain:import-character",
    SHOW_SAVE_DIALOG: "unchain:show-save-dialog",
    SHOW_OPEN_DIALOG: "unchain:show-open-dialog",
    WRITE_FILE: "unchain:write-file",
    READ_FILE: "unchain:read-file",
    STREAM_START: "unchain:stream:start",
    STREAM_START_V2: "unchain:stream:start-v2",
    STREAM_START_V3: "unchain:stream:start-v3",
    STREAM_CANCEL: "unchain:stream:cancel",
    STREAM_EVENT: "unchain:stream:event",
    RUNTIME_LOG: "unchain:runtime-log",
  }),
  THEME: Object.freeze({
    SET_BACKGROUND_COLOR: "theme-set-background-color",
    SET_MODE: "theme-set-mode",
  }),
  WINDOW_STATE: Object.freeze({
    HANDLE_ACTION: "window-state-event-handler",
    LISTENER_EVENT: "window-state-event-listener",
  }),
  SCREENSHOT: Object.freeze({
    CAPTURE: "screenshot:capture",
    CHECK_AVAILABILITY: "screenshot:check-availability",
  }),
  TEST_BRIDGE: Object.freeze({
    INVOKE: "test-bridge:invoke",
    RESULT: "test-bridge:result",
    LOG: "test-bridge:log",
    EVENT: "test-bridge:event",
    READY: "test-bridge:ready",
  }),
});

module.exports = {
  CHANNELS,
};
